### ISSUE TITLE
Criar telas iniciais

### ISSUE THREAD

**Issue by lucasviinic** [lucasviinic/flashcard_forge_app#1]
### Tasks 

- [x] Criar splash screen
- [x] Criar AppBar (drower menu, logo e search option)
- [x] Criar home
- [x] Criar container dos subjects
- [x] Implementar opção de criar tópicos dentro dos subjects
- [ ] Criar tela de tópicos (É nela que ficará os flashcards)
- [ ] Criar tela de cadastro
- [ ] Criar tela de login
- [ ] Criar tela de recuperação de senha
